Repository databricks/databricks-cli, pull requests merged in 2022-05, with the labels that each got.

#450 Add devcontainer configuration
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: LGTM

#448 Sample - Fix exports from Workspace to Windows FS
  databricks_cli/workspace/api.py
Labels: bug, windows

#385 Relax requirement for specification of Git provider for Repos
  databricks_cli/repos/cli.py
  databricks_cli/sdk/service.py
  tests/repos/test_api.py
  tests/repos/test_cli.py
  tests/sdk/test_api_client.py
Labels: UX
